language: php

dist: trusty

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

before_script:
  - if [[ $PHPCS = 1 ]]; then composer install; fi
  - if [[ $PHPCS != 1 ]]; then composer run-script post-install-cmd --no-interaction; fi

script:
  - if [[ $PHPCS != 1 ]]; then phpunit; fi

notifications:
  email: false
